// Fixture content for the seeded tenants.
//
// Pure data — no I/O, no Supabase. `index.mjs` resolves the cross-references
// by `key` and writes the rows. Keeping the content here means editing the
// demo story (names, amounts, statuses) never means touching the seed logic.
//
// Tenant identity — the organisation row, the login addresses, the shared
// password — lives in profiles.mjs, so this one story can be seeded into more
// than one organisation.

// `slot` is a stable, role-descriptive handle used to build login aliases. It
// is deliberately independent of the person's name so the addresses in a
// handed-out login package survive a rename of the fixture staff.
export const TEAM = [
  { key: 'dana', slot: 'owner', first: 'Dana', last: 'Whitfield', role: 'tenant_owner', phone: '(303) 555-0101' },
  { key: 'marcus', slot: 'admin', first: 'Marcus', last: 'Reyes', role: 'admin', phone: '(303) 555-0102' },
  { key: 'priya', slot: 'estimator1', first: 'Priya', last: 'Raman', role: 'estimator', phone: '(303) 555-0103' },
  { key: 'elena', slot: 'estimator2', first: 'Elena', last: 'Vasquez', role: 'estimator', phone: '(303) 555-0104' },
  { key: 'tony', slot: 'tech1', first: 'Tony', last: 'Delgado', role: 'technician', phone: '(303) 555-0105' },
  { key: 'sam', slot: 'tech2', first: 'Sam', last: 'Okafor', role: 'technician', phone: '(303) 555-0106' },
  { key: 'rachel', slot: 'viewer', first: 'Rachel', last: 'Kim', role: 'viewer', phone: '(303) 555-0107' },
]

export const COMPANIES = [
  {
    key: 'cherrycreek',
    name: 'Cherry Creek Property Group',
    company_type: 'commercial_property_mgr',
    account_status: 'active',
    industry: 'Property Management',
    website: 'https://cherrycreekpg.com',
    primary_phone: '(303) 555-0210',
    primary_email: 'mark.hope+demo.cherrycreek@asymmetric.pro',
    billing_address_line1: '2600 E 1st Avenue, Suite 300',
    billing_city: 'Denver',
    billing_state: 'CO',
    billing_zip: '80206',
    payment_terms: 'net_30',
    lead_source: 'referral',
    customer_since: '2024-03-11',
    ownerKey: 'dana',
  },
  {
    key: 'frontrange',
    name: 'Front Range School District 14',
    company_type: 'government',
    account_status: 'active',
    industry: 'Public Education',
    primary_phone: '(303) 555-0220',
    primary_email: 'mark.hope+demo.frsd@asymmetric.pro',
    billing_address_line1: '5291 E 60th Avenue',
    billing_city: 'Commerce City',
    billing_state: 'CO',
    billing_zip: '80022',
    payment_terms: 'net_45',
    lead_source: 'public_bid',
    customer_since: '2023-08-02',
    ownerKey: 'dana',
  },
  {
    key: 'alpineridge',
    name: 'Alpine Ridge HOA',
    company_type: 'hoa',
    account_status: 'active',
    industry: 'Residential Association',
    primary_phone: '(303) 555-0230',
    primary_email: 'mark.hope+demo.alpineridge@asymmetric.pro',
    billing_address_line1: '1180 Jasmine Street',
    billing_city: 'Denver',
    billing_state: 'CO',
    billing_zip: '80220',
    payment_terms: 'net_30',
    lead_source: 'website',
    customer_since: '2025-01-20',
    ownerKey: 'marcus',
  },
  {
    key: 'kessler',
    name: 'Kessler General Contracting',
    company_type: 'general_contractor',
    account_status: 'active',
    industry: 'Construction',
    website: 'https://kesslergc.com',
    primary_phone: '(303) 555-0240',
    primary_email: 'mark.hope+demo.kessler@asymmetric.pro',
    billing_address_line1: '7745 W Colfax Avenue',
    billing_city: 'Lakewood',
    billing_state: 'CO',
    billing_zip: '80214',
    payment_terms: 'net_30',
    lead_source: 'referral',
    customer_since: '2024-09-15',
    ownerKey: 'marcus',
  },
  {
    key: 'baseline',
    name: 'Baseline Industrial Park',
    company_type: 'industrial',
    account_status: 'prospect',
    industry: 'Light Industrial',
    primary_phone: '(303) 555-0250',
    primary_email: 'mark.hope+demo.baseline@asymmetric.pro',
    billing_address_line1: '3300 Arapahoe Avenue',
    billing_city: 'Boulder',
    billing_state: 'CO',
    billing_zip: '80303',
    payment_terms: 'net_30',
    lead_source: 'trade_show',
    ownerKey: 'dana',
  },
]

export const CONTACTS = [
  {
    key: 'karen',
    first_name: 'Karen',
    last_name: 'Mulvaney',
    companyKey: 'cherrycreek',
    contact_type: 'commercial',
    contact_role: 'decision_maker',
    title: 'Director of Facilities',
    email: 'mark.hope+demo.karen@asymmetric.pro',
    mobile_phone: '(303) 555-0211',
    office_phone: '(303) 555-0210',
    status: 'customer',
    address_line1: '2600 E 1st Avenue, Suite 300',
    city: 'Denver',
    state: 'CO',
    zip: '80206',
    lead_source: 'referral',
    is_primary_contact: true,
    ownerKey: 'dana',
  },
  {
    key: 'doug',
    first_name: 'Doug',
    last_name: 'Pham',
    companyKey: 'cherrycreek',
    contact_type: 'commercial',
    contact_role: 'site_contact',
    title: 'Building Superintendent',
    email: 'mark.hope+demo.doug@asymmetric.pro',
    mobile_phone: '(303) 555-0212',
    status: 'customer',
    address_line1: '2600 E 1st Avenue, Suite 300',
    city: 'Denver',
    state: 'CO',
    zip: '80206',
    lead_source: 'referral',
    ownerKey: 'dana',
  },
  {
    key: 'yvonne',
    first_name: 'Yvonne',
    last_name: 'Castellanos',
    companyKey: 'frontrange',
    contact_type: 'commercial',
    contact_role: 'decision_maker',
    title: 'Facilities Operations Manager',
    email: 'mark.hope+demo.yvonne@asymmetric.pro',
    mobile_phone: '(303) 555-0221',
    office_phone: '(303) 555-0220',
    status: 'customer',
    address_line1: '5291 E 60th Avenue',
    city: 'Commerce City',
    state: 'CO',
    zip: '80022',
    lead_source: 'public_bid',
    is_primary_contact: true,
    ownerKey: 'dana',
  },
  {
    key: 'ray',
    first_name: 'Ray',
    last_name: 'Okonkwo',
    companyKey: 'alpineridge',
    contact_type: 'commercial',
    contact_role: 'decision_maker',
    title: 'HOA Board President',
    email: 'mark.hope+demo.ray@asymmetric.pro',
    mobile_phone: '(303) 555-0231',
    status: 'customer',
    address_line1: '1180 Jasmine Street',
    city: 'Denver',
    state: 'CO',
    zip: '80220',
    lead_source: 'website',
    is_primary_contact: true,
    ownerKey: 'marcus',
  },
  {
    key: 'bill',
    first_name: 'Bill',
    last_name: 'Kessler',
    companyKey: 'kessler',
    contact_type: 'commercial',
    contact_role: 'decision_maker',
    title: 'Owner',
    email: 'mark.hope+demo.bill@asymmetric.pro',
    mobile_phone: '(303) 555-0241',
    office_phone: '(303) 555-0240',
    status: 'customer',
    address_line1: '7745 W Colfax Avenue',
    city: 'Lakewood',
    state: 'CO',
    zip: '80214',
    lead_source: 'referral',
    is_primary_contact: true,
    ownerKey: 'marcus',
  },
  {
    key: 'nina',
    first_name: 'Nina',
    last_name: 'Alvarez',
    companyKey: 'baseline',
    contact_type: 'commercial',
    contact_role: 'decision_maker',
    title: 'Property Manager',
    email: 'mark.hope+demo.baseline@asymmetric.pro',
    mobile_phone: '(303) 555-0251',
    status: 'prospect',
    address_line1: '3300 Arapahoe Avenue',
    city: 'Boulder',
    state: 'CO',
    zip: '80303',
    lead_source: 'trade_show',
    is_primary_contact: true,
    ownerKey: 'dana',
  },
  {
    key: 'gregory',
    first_name: 'Gregory',
    last_name: 'Hahn',
    companyKey: null,
    contact_type: 'residential',
    contact_role: 'decision_maker',
    email: 'mark.hope+demo.gregory@asymmetric.pro',
    mobile_phone: '(720) 555-0301',
    status: 'customer',
    address_line1: '1427 S Clarkson Street',
    city: 'Denver',
    state: 'CO',
    zip: '80210',
    lead_source: 'website',
    ownerKey: 'priya',
  },
  {
    key: 'marisol',
    first_name: 'Marisol',
    last_name: 'Duarte',
    companyKey: null,
    contact_type: 'residential',
    contact_role: 'decision_maker',
    email: 'mark.hope+demo.marisol@asymmetric.pro',
    mobile_phone: '(720) 555-0302',
    status: 'customer',
    address_line1: '3390 W 32nd Avenue',
    city: 'Denver',
    state: 'CO',
    zip: '80211',
    lead_source: 'referral',
    ownerKey: 'elena',
  },
  {
    key: 'peter',
    first_name: 'Peter',
    last_name: 'Lindqvist',
    companyKey: null,
    contact_type: 'residential',
    contact_role: 'decision_maker',
    email: 'mark.hope+demo.peter@asymmetric.pro',
    mobile_phone: '(720) 555-0303',
    status: 'prospect',
    address_line1: '860 Marion Street',
    city: 'Denver',
    state: 'CO',
    zip: '80218',
    lead_source: 'phone',
    ownerKey: 'priya',
  },
  {
    // Sold 1427 S Clarkson to Gregory Hahn in 2024. Kept on the property
    // record as the previous owner — he's who to ask about work that
    // predates the current owner.
    key: 'harold',
    first_name: 'Harold',
    last_name: 'Vance',
    companyKey: null,
    contact_type: 'residential',
    contact_role: 'other',
    email: 'mark.hope+demo.harold@asymmetric.pro',
    mobile_phone: '(720) 555-0305',
    status: 'past_customer',
    address_line1: '4102 E Amherst Avenue',
    city: 'Denver',
    state: 'CO',
    zip: '80222',
    lead_source: 'referral',
    ownerKey: 'priya',
  },
  {
    key: 'angela',
    first_name: 'Angela',
    last_name: 'Boone',
    companyKey: null,
    contact_type: 'residential',
    contact_role: 'decision_maker',
    email: 'mark.hope+demo.angela@asymmetric.pro',
    mobile_phone: '(720) 555-0304',
    status: 'inquiry',
    address_line1: '2214 Eudora Street',
    city: 'Denver',
    state: 'CO',
    zip: '80207',
    lead_source: 'website',
    ownerKey: 'elena',
  },
]

// `dayOffset` is relative to the seed run date; negative is in the past.
export const OPPORTUNITIES = [
  {
    key: 'opp-alpine-boiler',
    propertyKey: 'prop-jasmine',
    name: 'Alpine Ridge — boiler room TSI removal',
    contactKey: 'ray',
    companyKey: 'alpineridge',
    stage: 'Won',
    opportunity_status: 'won',
    estimated_value: 48500,
    probability_pct: 100,
    hazard_types: ['asbestos'],
    property_type: 'residential_multi_family',
    property_age: 47,
    urgency: 'routine',
    regulatory_trigger: 'inspection_required',
    closeOffset: -24,
    ownerKey: 'marcus',
    service_address_line1: '1180 Jasmine Street',
    service_city: 'Denver',
    service_state: 'CO',
    service_zip: '80220',
  },
  {
    key: 'opp-frsd-tile',
    propertyKey: 'prop-holly',
    name: 'FRSD 14 — Adams Elementary floor tile abatement',
    contactKey: 'yvonne',
    companyKey: 'frontrange',
    stage: 'Won',
    opportunity_status: 'won',
    estimated_value: 122400,
    probability_pct: 100,
    hazard_types: ['asbestos'],
    property_type: 'government',
    property_age: 58,
    urgency: 'routine',
    regulatory_trigger: 'inspection_required',
    closeOffset: -46,
    ownerKey: 'dana',
    service_address_line1: '6500 Holly Street',
    service_city: 'Commerce City',
    service_state: 'CO',
    service_zip: '80022',
  },
  {
    key: 'opp-cherry-transite',
    propertyKey: 'prop-steele',
    name: 'Cherry Creek — 4-plex transite siding removal',
    contactKey: 'karen',
    companyKey: 'cherrycreek',
    stage: 'Negotiation',
    opportunity_status: 'estimate_sent',
    estimated_value: 67800,
    probability_pct: 75,
    hazard_types: ['asbestos'],
    property_type: 'residential_multi_family',
    property_age: 52,
    urgency: 'routine',
    regulatory_trigger: 'sale_pending',
    closeOffset: 14,
    ownerKey: 'dana',
    service_address_line1: '1455 Steele Street',
    service_city: 'Denver',
    service_state: 'CO',
    service_zip: '80206',
  },
  {
    key: 'opp-kessler-lead',
    propertyKey: 'prop-curtis',
    name: 'Kessler GC — lead paint stabilization, Curtis St',
    contactKey: 'bill',
    companyKey: 'kessler',
    stage: 'Proposal Sent',
    opportunity_status: 'estimate_sent',
    estimated_value: 31250,
    probability_pct: 50,
    hazard_types: ['lead'],
    property_type: 'commercial',
    property_age: 71,
    urgency: 'urgent',
    regulatory_trigger: 'voluntary',
    closeOffset: 9,
    ownerKey: 'marcus',
    service_address_line1: '2100 Curtis Street',
    service_city: 'Denver',
    service_state: 'CO',
    service_zip: '80205',
  },
  {
    key: 'opp-hahn-vermiculite',
    propertyKey: 'prop-clarkson',
    name: 'Hahn residence — attic vermiculite removal',
    contactKey: 'gregory',
    companyKey: null,
    stage: 'Proposal Sent',
    opportunity_status: 'estimate_sent',
    estimated_value: 14900,
    probability_pct: 50,
    hazard_types: ['vermiculite'],
    property_type: 'residential_single_family',
    property_age: 68,
    urgency: 'routine',
    regulatory_trigger: 'sale_pending',
    closeOffset: 6,
    ownerKey: 'priya',
    service_address_line1: '1427 S Clarkson Street',
    service_city: 'Denver',
    service_state: 'CO',
    service_zip: '80210',
  },
  {
    key: 'opp-duarte-mold',
    propertyKey: 'prop-32nd',
    name: 'Duarte residence — basement mold remediation',
    contactKey: 'marisol',
    companyKey: null,
    stage: 'Qualified',
    opportunity_status: 'survey_completed',
    estimated_value: 8750,
    probability_pct: 25,
    hazard_types: ['mold'],
    property_type: 'residential_single_family',
    property_age: 39,
    urgency: 'urgent',
    regulatory_trigger: 'insurance_claim',
    closeOffset: 18,
    ownerKey: 'elena',
    service_address_line1: '3390 W 32nd Avenue',
    service_city: 'Denver',
    service_state: 'CO',
    service_zip: '80211',
  },
  {
    key: 'opp-baseline-survey',
    propertyKey: 'prop-arapahoe',
    name: 'Baseline Industrial — pre-demolition asbestos survey',
    contactKey: 'nina',
    companyKey: 'baseline',
    stage: 'Qualified',
    opportunity_status: 'assessment_scheduled',
    estimated_value: 96000,
    probability_pct: 25,
    hazard_types: ['asbestos', 'lead'],
    property_type: 'industrial',
    property_age: 63,
    urgency: 'routine',
    regulatory_trigger: 'inspection_required',
    closeOffset: 41,
    ownerKey: 'dana',
    service_address_line1: '3300 Arapahoe Avenue',
    service_city: 'Boulder',
    service_state: 'CO',
    service_zip: '80303',
  },
  {
    key: 'opp-boone-inquiry',
    propertyKey: 'prop-eudora',
    name: 'Boone residence — popcorn ceiling testing',
    contactKey: 'angela',
    companyKey: null,
    stage: 'New Lead',
    opportunity_status: 'new',
    estimated_value: 4200,
    probability_pct: 10,
    hazard_types: ['asbestos'],
    property_type: 'residential_single_family',
    property_age: 44,
    urgency: 'routine',
    regulatory_trigger: 'voluntary',
    closeOffset: 30,
    ownerKey: 'elena',
    service_address_line1: '2214 Eudora Street',
    service_city: 'Denver',
    service_state: 'CO',
    service_zip: '80207',
  },
  {
    key: 'opp-lindqvist-lost',
    propertyKey: 'prop-marion',
    name: 'Lindqvist residence — duct insulation removal',
    contactKey: 'peter',
    companyKey: null,
    stage: 'Lost',
    opportunity_status: 'lost',
    estimated_value: 11400,
    probability_pct: 0,
    hazard_types: ['asbestos'],
    property_type: 'residential_single_family',
    property_age: 61,
    urgency: 'routine',
    regulatory_trigger: 'voluntary',
    closeOffset: -11,
    ownerKey: 'priya',
    outcome: 'lost',
    loss_reason: 'price',
    loss_notes: 'Went with a lower bid that excluded clearance testing. Follow up in Q4.',
    competitor: 'Mile High Environmental',
    service_address_line1: '860 Marion Street',
    service_city: 'Denver',
    service_state: 'CO',
    service_zip: '80218',
  },
]

export const SURVEYS = [
  {
    key: 'srv-alpine',
    propertyKey: 'prop-jasmine',
    oppKey: 'opp-alpine-boiler',
    contactKey: 'ray',
    job_name: 'Alpine Ridge — boiler room TSI',
    hazard_type: 'asbestos',
    hazard_subtype: 'Thermal system insulation',
    status: 'completed',
    estimatorKey: 'marcus',
    area_sqft: 340,
    linear_ft: 210,
    containment_level: 3,
    material_type: 'Pipe lagging / mudded fittings',
    building_type: 'Multi-family residential',
    year_built: 1979,
    building_sqft: 28400,
    stories: 3,
    occupied: true,
    clearance_required: true,
    clearance_lab: 'Rocky Mountain Analytical',
    regulatory_notifications_needed: true,
    scheduledOffset: -38,
    photos: 4,
    notes: 'Boiler room and adjacent mechanical chase. TSI on horizontal runs and 14 mudded fittings. Access via basement stair only — no exterior door.',
  },
  {
    key: 'srv-frsd',
    propertyKey: 'prop-holly',
    oppKey: 'opp-frsd-tile',
    contactKey: 'yvonne',
    job_name: 'Adams Elementary — 9x9 floor tile & mastic',
    hazard_type: 'asbestos',
    hazard_subtype: 'Floor tile and mastic',
    status: 'completed',
    estimatorKey: 'dana',
    area_sqft: 11200,
    containment_level: 2,
    material_type: '9x9 VAT over black mastic',
    building_type: 'School',
    year_built: 1968,
    building_sqft: 64000,
    stories: 1,
    occupied: false,
    clearance_required: true,
    clearance_lab: 'Rocky Mountain Analytical',
    regulatory_notifications_needed: true,
    scheduledOffset: -61,
    photos: 5,
    notes: 'Summer shutdown window. Classrooms 100-118 plus main corridor. District requires clearance before staff return 8/12.',
  },
  {
    key: 'srv-cherry',
    propertyKey: 'prop-steele',
    oppKey: 'opp-cherry-transite',
    contactKey: 'karen',
    job_name: 'Steele St 4-plex — transite siding',
    hazard_type: 'asbestos',
    hazard_subtype: 'Transite siding',
    status: 'estimated',
    estimatorKey: 'dana',
    area_sqft: 4100,
    containment_level: 2,
    material_type: 'Cementitious transite panel',
    building_type: 'Multi-family residential',
    year_built: 1973,
    building_sqft: 5200,
    stories: 2,
    occupied: true,
    clearance_required: false,
    regulatory_notifications_needed: true,
    scheduledOffset: -16,
    photos: 3,
    notes: 'All four elevations. Panels largely intact, some impact damage on the north face. Tenants remain in place — negative-pressure not required for exterior.',
  },
  {
    key: 'srv-kessler',
    propertyKey: 'prop-curtis',
    oppKey: 'opp-kessler-lead',
    contactKey: 'bill',
    job_name: 'Curtis St — lead paint stabilization',
    hazard_type: 'lead',
    hazard_subtype: 'Deteriorated painted surfaces',
    status: 'estimated',
    estimatorKey: 'marcus',
    area_sqft: 2600,
    containment_level: 2,
    material_type: 'Lead-based paint on plaster and trim',
    building_type: 'Commercial',
    year_built: 1955,
    building_sqft: 9800,
    stories: 2,
    occupied: false,
    clearance_required: true,
    clearance_lab: 'Front Range Testing',
    regulatory_notifications_needed: false,
    scheduledOffset: -12,
    photos: 3,
    notes: 'Second-floor offices ahead of tenant fit-out. XRF confirmed on window trim and door casings.',
  },
  {
    key: 'srv-hahn',
    propertyKey: 'prop-clarkson',
    oppKey: 'opp-hahn-vermiculite',
    contactKey: 'gregory',
    job_name: 'Hahn residence — attic vermiculite',
    hazard_type: 'vermiculite',
    hazard_subtype: 'Loose-fill attic insulation',
    status: 'estimated',
    estimatorKey: 'priya',
    area_sqft: 1180,
    volume_cuft: 590,
    containment_level: 3,
    material_type: 'Zonolite loose-fill',
    building_type: 'Single-family residential',
    year_built: 1958,
    building_sqft: 1980,
    stories: 1,
    occupied: true,
    clearance_required: true,
    clearance_lab: 'Rocky Mountain Analytical',
    regulatory_notifications_needed: true,
    scheduledOffset: -9,
    photos: 4,
    notes: 'Attic access from hallway hatch only. Homeowner selling — needs clearance letter before closing on 9/12.',
  },
  {
    key: 'srv-duarte',
    propertyKey: 'prop-32nd',
    oppKey: 'opp-duarte-mold',
    contactKey: 'marisol',
    job_name: 'Duarte residence — basement mold',
    hazard_type: 'mold',
    hazard_subtype: 'Water-damage growth on framing and drywall',
    status: 'submitted',
    estimatorKey: 'elena',
    area_sqft: 620,
    containment_level: 2,
    material_type: 'Gypsum board and dimensional framing',
    building_type: 'Single-family residential',
    year_built: 1987,
    building_sqft: 2240,
    stories: 2,
    occupied: true,
    clearance_required: true,
    clearance_lab: 'Front Range Testing',
    regulatory_notifications_needed: false,
    scheduledOffset: -4,
    photos: 3,
    notes: 'Sewer backup in April. Insurance claim open with Travelers — adjuster wants scope and post-remediation verification.',
  },
  {
    key: 'srv-baseline',
    propertyKey: 'prop-arapahoe',
    oppKey: 'opp-baseline-survey',
    contactKey: 'nina',
    job_name: 'Baseline Industrial — pre-demo survey',
    hazard_type: 'asbestos',
    hazard_subtype: 'Multiple suspect materials',
    status: 'scheduled',
    estimatorKey: 'dana',
    containment_level: 2,
    building_type: 'Industrial',
    year_built: 1963,
    building_sqft: 41000,
    stories: 1,
    occupied: false,
    clearance_required: false,
    regulatory_notifications_needed: true,
    scheduledOffset: 5,
    photos: 0,
    notes: 'Full pre-demolition survey ahead of redevelopment. Roofing, TSI, floor tile and transite partitions all suspect.',
  },
  {
    key: 'srv-boone',
    propertyKey: 'prop-eudora',
    oppKey: 'opp-boone-inquiry',
    contactKey: 'angela',
    job_name: 'Boone residence — ceiling texture sampling',
    hazard_type: 'asbestos',
    hazard_subtype: 'Acoustic ceiling texture',
    status: 'draft',
    estimatorKey: 'elena',
    building_type: 'Single-family residential',
    year_built: 1982,
    building_sqft: 1640,
    stories: 1,
    occupied: true,
    clearance_required: false,
    regulatory_notifications_needed: false,
    scheduledOffset: 11,
    photos: 0,
    notes: 'Homeowner wants sampling before a kitchen remodel. Three-sample composite quoted.',
  },
]

const lineItem = (item_type, category, description, quantity, unit, unit_price) => ({
  item_type,
  category,
  description,
  quantity,
  unit,
  unit_price,
})

export const ESTIMATES = [
  {
    key: 'est-alpine',
    surveyKey: 'srv-alpine',
    contactKey: 'ray',
    status: 'converted',
    project_name: 'Alpine Ridge boiler room TSI abatement',
    createdOffset: -34,
    validDays: 30,
    estimated_duration_days: 5,
    createdByKey: 'marcus',
    scope_of_work:
      'Full removal of asbestos-containing thermal system insulation from boiler room piping and mudded fittings under Type III containment, including negative air, HEPA filtration, disposal at a permitted facility, and third-party clearance air monitoring.',
    markup_percent: 18,
    tax_percent: 0,
    lineItems: [
      lineItem('labor', 'Abatement', 'Certified abatement crew — 4 workers', 160, 'hour', 78),
      lineItem('labor', 'Supervision', 'Competent person / site supervisor', 40, 'hour', 96),
      lineItem('equipment', 'Containment', 'Negative air machines and HEPA filtration', 5, 'day', 340),
      lineItem('material', 'Containment', '6-mil poly, spray adhesive, glovebags', 1, 'lot', 2150),
      lineItem('disposal', 'Waste', 'ACM disposal — permitted landfill, manifested', 6, 'cubic yard', 385),
      lineItem('testing', 'Clearance', 'Third-party clearance air sampling (5 samples)', 5, 'sample', 165),
      lineItem('permit', 'Regulatory', 'CDPHE notification and permit', 1, 'each', 375),
    ],
  },
  {
    key: 'est-frsd',
    surveyKey: 'srv-frsd',
    contactKey: 'yvonne',
    status: 'converted',
    project_name: 'Adams Elementary floor tile and mastic abatement',
    createdOffset: -56,
    validDays: 45,
    estimated_duration_days: 12,
    createdByKey: 'dana',
    scope_of_work:
      'Removal of approximately 11,200 sq ft of 9x9 vinyl asbestos tile and associated black mastic from classrooms 100-118 and the main corridor under Type II containment. Includes mastic remediation, disposal, and clearance prior to staff return.',
    markup_percent: 15,
    tax_percent: 0,
    lineItems: [
      lineItem('labor', 'Abatement', 'Certified abatement crew — 6 workers', 576, 'hour', 76),
      lineItem('labor', 'Supervision', 'Competent person / site supervisor', 96, 'hour', 96),
      lineItem('equipment', 'Containment', 'Negative air machines and HEPA filtration', 12, 'day', 420),
      lineItem('equipment', 'Removal', 'Mastic removal equipment and scrapers', 12, 'day', 180),
      lineItem('material', 'Containment', 'Poly sheeting, adhesive remover, consumables', 1, 'lot', 6400),
      lineItem('disposal', 'Waste', 'ACM disposal — permitted landfill, manifested', 22, 'cubic yard', 385),
      lineItem('testing', 'Clearance', 'Third-party clearance air sampling (18 samples)', 18, 'sample', 165),
      lineItem('permit', 'Regulatory', 'CDPHE notification and permit', 1, 'each', 375),
    ],
  },
  {
    key: 'est-cherry',
    surveyKey: 'srv-cherry',
    contactKey: 'karen',
    status: 'sent',
    project_name: 'Steele Street transite siding removal',
    createdOffset: -13,
    validDays: 30,
    estimated_duration_days: 6,
    createdByKey: 'dana',
    scope_of_work:
      'Removal and disposal of approximately 4,100 sq ft of asbestos-cement transite siding from all four elevations, including ground-level poly capture, manifested disposal, and CDPHE notification. Tenants remain in occupancy throughout.',
    markup_percent: 18,
    tax_percent: 0,
    lineItems: [
      lineItem('labor', 'Abatement', 'Certified abatement crew — 4 workers', 192, 'hour', 78),
      lineItem('labor', 'Supervision', 'Competent person / site supervisor', 48, 'hour', 96),
      lineItem('equipment', 'Access', 'Scaffold and lift rental', 6, 'day', 520),
      lineItem('material', 'Containment', 'Ground poly, encapsulant, fasteners', 1, 'lot', 3100),
      lineItem('disposal', 'Waste', 'ACM disposal — permitted landfill, manifested', 14, 'cubic yard', 385),
      lineItem('permit', 'Regulatory', 'CDPHE notification and permit', 1, 'each', 375),
    ],
  },
  {
    key: 'est-kessler',
    surveyKey: 'srv-kessler',
    contactKey: 'bill',
    status: 'sent',
    project_name: 'Curtis Street lead paint stabilization',
    createdOffset: -8,
    validDays: 30,
    estimated_duration_days: 4,
    createdByKey: 'marcus',
    scope_of_work:
      'Stabilization of deteriorated lead-based paint on second-floor window trim, door casings and plaster walls. Includes wet scraping, encapsulation, HEPA cleaning, and third-party clearance wipe sampling.',
    markup_percent: 20,
    tax_percent: 0,
    lineItems: [
      lineItem('labor', 'Abatement', 'Lead-certified crew — 3 workers', 96, 'hour', 72),
      lineItem('labor', 'Supervision', 'Competent person / site supervisor', 32, 'hour', 96),
      lineItem('material', 'Encapsulation', 'Encapsulant, stabilizing primer, consumables', 1, 'lot', 2400),
      lineItem('equipment', 'Containment', 'HEPA vacuums and poly containment', 4, 'day', 240),
      lineItem('disposal', 'Waste', 'Lead waste disposal — manifested', 3, 'cubic yard', 340),
      lineItem('testing', 'Clearance', 'Clearance wipe sampling (12 samples)', 12, 'sample', 95),
    ],
  },
  {
    key: 'est-hahn',
    surveyKey: 'srv-hahn',
    contactKey: 'gregory',
    status: 'sent',
    project_name: 'Hahn residence attic vermiculite removal',
    createdOffset: -6,
    validDays: 30,
    estimated_duration_days: 3,
    createdByKey: 'priya',
    scope_of_work:
      'Removal of approximately 590 cubic feet of Zonolite loose-fill vermiculite insulation from the attic under Type III containment, including HEPA vacuum extraction, manifested disposal, and clearance air sampling for the pending property sale.',
    markup_percent: 20,
    tax_percent: 0,
    lineItems: [
      lineItem('labor', 'Abatement', 'Certified abatement crew — 3 workers', 72, 'hour', 78),
      lineItem('labor', 'Supervision', 'Competent person / site supervisor', 24, 'hour', 96),
      lineItem('equipment', 'Extraction', 'HEPA vacuum extraction unit', 3, 'day', 480),
      lineItem('equipment', 'Containment', 'Negative air and decontamination unit', 3, 'day', 340),
      lineItem('material', 'Containment', 'Poly, glovebags, disposal bags', 1, 'lot', 1250),
      lineItem('disposal', 'Waste', 'ACM disposal — permitted landfill, manifested', 5, 'cubic yard', 385),
      lineItem('testing', 'Clearance', 'Clearance air sampling (4 samples)', 4, 'sample', 165),
      lineItem('permit', 'Regulatory', 'CDPHE notification and permit', 1, 'each', 375),
    ],
  },
  {
    key: 'est-duarte',
    surveyKey: 'srv-duarte',
    contactKey: 'marisol',
    status: 'draft',
    project_name: 'Duarte residence basement mold remediation',
    createdOffset: -2,
    validDays: 30,
    estimated_duration_days: 3,
    createdByKey: 'elena',
    scope_of_work:
      'Remediation of approximately 620 sq ft of mold-affected drywall and framing in the finished basement following a sewer backup. Includes containment, material removal, antimicrobial treatment, HEPA cleaning and post-remediation verification.',
    markup_percent: 22,
    tax_percent: 0,
    lineItems: [
      lineItem('labor', 'Remediation', 'Remediation crew — 3 workers', 72, 'hour', 68),
      lineItem('labor', 'Supervision', 'Project supervisor', 16, 'hour', 92),
      lineItem('equipment', 'Drying', 'Air scrubbers and dehumidifiers', 3, 'day', 290),
      lineItem('material', 'Treatment', 'Antimicrobial, poly, consumables', 1, 'lot', 780),
      lineItem('disposal', 'Waste', 'Construction debris disposal', 4, 'cubic yard', 145),
      lineItem('testing', 'Clearance', 'Post-remediation verification sampling', 3, 'sample', 185),
    ],
  },
]

export const PROPOSALS = [
  {
    key: 'prop-alpine',
    estimateKey: 'est-alpine',
    contactKey: 'ray',
    status: 'signed',
    createdOffset: -31,
    sentOffset: -30,
    viewedOffset: -29,
    signedOffset: -26,
    signer_name: 'Ray Okonkwo',
    signer_email: 'mark.hope+demo.ray@asymmetric.pro',
    viewed_count: 4,
    createdByKey: 'marcus',
  },
  {
    key: 'prop-frsd',
    estimateKey: 'est-frsd',
    contactKey: 'yvonne',
    status: 'signed',
    createdOffset: -53,
    sentOffset: -52,
    viewedOffset: -51,
    signedOffset: -48,
    signer_name: 'Yvonne Castellanos',
    signer_email: 'mark.hope+demo.yvonne@asymmetric.pro',
    viewed_count: 7,
    createdByKey: 'dana',
  },
  {
    key: 'prop-cherry',
    estimateKey: 'est-cherry',
    contactKey: 'karen',
    status: 'viewed',
    createdOffset: -11,
    sentOffset: -10,
    viewedOffset: -3,
    viewed_count: 3,
    createdByKey: 'dana',
  },
  {
    key: 'prop-kessler',
    estimateKey: 'est-kessler',
    contactKey: 'bill',
    status: 'sent',
    createdOffset: -7,
    sentOffset: -6,
    viewed_count: 0,
    createdByKey: 'marcus',
  },
  {
    key: 'prop-hahn',
    estimateKey: 'est-hahn',
    contactKey: 'gregory',
    status: 'draft',
    createdOffset: -5,
    viewed_count: 0,
    createdByKey: 'priya',
  },
]

export const JOBS = [
  {
    key: 'job-frsd',
    propertyKey: 'prop-holly',
    proposalKey: 'prop-frsd',
    estimateKey: 'est-frsd',
    surveyKey: 'srv-frsd',
    oppKey: 'opp-frsd-tile',
    contactKey: 'yvonne',
    companyKey: 'frontrange',
    name: 'Adams Elementary — floor tile abatement',
    status: 'completed',
    hazard_types: ['asbestos'],
    containment_level: 'type_ii',
    startOffset: -44,
    durationDays: 12,
    crewLeadKey: 'tony',
    address: { line1: '6500 Holly Street', city: 'Commerce City', state: 'CO', zip: '80022' },
    contract_amount: 122400,
    estimated_revenue: 122400,
    actual_revenue: 126850,
    estimated_cost: 84300,
    actual_cost: 86910,
    estimated_labor_hours: 672,
    actual_labor_hours: 704,
    actual_affected_area_sqft: 11450,
    permit_numbers: ['CDPHE-2026-04188'],
    disposal_manifest_numbers: ['MAN-2026-0619-A', 'MAN-2026-0621-B', 'MAN-2026-0624-C'],
    air_monitoring_required: true,
    clearance_testing_required: true,
    inspection_required: true,
    inspection_passed: true,
    customer_signed_off: true,
    signoff_name: 'Yvonne Castellanos',
    completion_notes:
      'All 19 rooms and the main corridor cleared on first pass. Change order for an additional 250 sq ft found under the built-in casework in room 112.',
    deposit_amount: 36720,
    depositOffset: -46,
    finalInvoiceOffset: -30,
    finalPaymentOffset: -12,
  },
  {
    key: 'job-alpine',
    propertyKey: 'prop-jasmine',
    proposalKey: 'prop-alpine',
    estimateKey: 'est-alpine',
    surveyKey: 'srv-alpine',
    oppKey: 'opp-alpine-boiler',
    contactKey: 'ray',
    companyKey: 'alpineridge',
    name: 'Alpine Ridge — boiler room TSI removal',
    status: 'completed',
    hazard_types: ['asbestos'],
    containment_level: 'type_iii',
    startOffset: -21,
    durationDays: 5,
    crewLeadKey: 'tony',
    address: { line1: '1180 Jasmine Street', city: 'Denver', state: 'CO', zip: '80220' },
    contract_amount: 48500,
    estimated_revenue: 48500,
    actual_revenue: 48500,
    estimated_cost: 33900,
    actual_cost: 32400,
    estimated_labor_hours: 200,
    actual_labor_hours: 191,
    actual_affected_area_sqft: 340,
    permit_numbers: ['CDPHE-2026-05012'],
    disposal_manifest_numbers: ['MAN-2026-0708-A'],
    air_monitoring_required: true,
    clearance_testing_required: true,
    inspection_required: true,
    inspection_passed: true,
    customer_signed_off: true,
    signoff_name: 'Ray Okonkwo',
    completion_notes:
      'Clearance passed first attempt at 0.004 f/cc. Board walked the space on 7/14 and signed off same day.',
    deposit_amount: 14550,
    depositOffset: -24,
    finalInvoiceOffset: -14,
    finalPaymentOffset: null,
  },
  {
    key: 'job-cherry-phase1',
    propertyKey: 'prop-steele',
    estimateKey: null,
    contactKey: 'karen',
    companyKey: 'cherrycreek',
    name: 'Cherry Creek — 1455 Steele St common area TSI',
    status: 'completed',
    hazard_types: ['asbestos'],
    containment_level: 'type_iii',
    startOffset: -74,
    durationDays: 4,
    crewLeadKey: 'sam',
    address: { line1: '1455 Steele Street', city: 'Denver', state: 'CO', zip: '80206' },
    contract_amount: 27300,
    estimated_revenue: 27300,
    actual_revenue: 27300,
    estimated_cost: 19100,
    actual_cost: 20450,
    estimated_labor_hours: 128,
    actual_labor_hours: 141,
    actual_affected_area_sqft: 210,
    permit_numbers: ['CDPHE-2026-03844'],
    disposal_manifest_numbers: ['MAN-2026-0515-A'],
    air_monitoring_required: true,
    clearance_testing_required: true,
    inspection_required: true,
    inspection_passed: true,
    customer_signed_off: true,
    signoff_name: 'Doug Pham',
    completion_notes:
      'Ran two days long — additional pipe runs behind the laundry room wall were not in the original scope. Absorbed at cost as a goodwill concession ahead of the siding bid.',
    deposit_amount: 8190,
    depositOffset: -77,
    finalInvoiceOffset: -68,
    finalPaymentOffset: -41,
  },
  {
    key: 'job-kessler-active',
    propertyKey: 'prop-curtis',
    contactKey: 'bill',
    companyKey: 'kessler',
    name: 'Kessler GC — Curtis St stairwell lead abatement',
    status: 'in_progress',
    hazard_types: ['lead'],
    containment_level: 'type_ii',
    startOffset: -3,
    durationDays: 6,
    crewLeadKey: 'sam',
    address: { line1: '2100 Curtis Street', city: 'Denver', state: 'CO', zip: '80205' },
    contract_amount: 18600,
    estimated_revenue: 18600,
    estimated_cost: 12900,
    estimated_labor_hours: 96,
    actual_labor_hours: 42,
    air_monitoring_required: false,
    clearance_testing_required: true,
    inspection_required: true,
    special_instructions:
      'Building occupied on floors 1 and 3 — no work before 8am. Freight elevator access only, gate code at the alley entrance.',
    deposit_amount: 5580,
    depositOffset: -6,
  },
  {
    key: 'job-alpine-phase2',
    propertyKey: 'prop-jasmine',
    contactKey: 'ray',
    companyKey: 'alpineridge',
    name: 'Alpine Ridge — unit 12B duct insulation',
    status: 'in_progress',
    hazard_types: ['asbestos'],
    containment_level: 'type_ii',
    startOffset: -1,
    durationDays: 3,
    crewLeadKey: 'tony',
    address: { line1: '1180 Jasmine Street, Unit 12B', city: 'Denver', state: 'CO', zip: '80220' },
    contract_amount: 9400,
    estimated_revenue: 9400,
    estimated_cost: 6300,
    estimated_labor_hours: 48,
    actual_labor_hours: 16,
    air_monitoring_required: true,
    clearance_testing_required: true,
    inspection_required: true,
    special_instructions: 'Resident relocated to a hotel through Thursday. Key at the management office.',
  },
  {
    key: 'job-cherry-siding',
    propertyKey: 'prop-steele',
    contactKey: 'karen',
    companyKey: 'cherrycreek',
    name: 'Cherry Creek — Steele St transite siding',
    status: 'scheduled',
    hazard_types: ['asbestos'],
    containment_level: 'type_ii',
    startOffset: 12,
    durationDays: 6,
    crewLeadKey: 'tony',
    address: { line1: '1455 Steele Street', city: 'Denver', state: 'CO', zip: '80206' },
    contract_amount: 67800,
    estimated_revenue: 67800,
    estimated_cost: 46200,
    estimated_labor_hours: 240,
    air_monitoring_required: false,
    clearance_testing_required: false,
    inspection_required: true,
    special_instructions:
      'Tenants remain in occupancy. Notices posted 10 days prior. Scaffold delivery the Friday before.',
  },
  {
    key: 'job-hahn-scheduled',
    propertyKey: 'prop-clarkson',
    contactKey: 'gregory',
    companyKey: null,
    name: 'Hahn residence — attic vermiculite removal',
    status: 'scheduled',
    hazard_types: ['vermiculite'],
    containment_level: 'type_iii',
    startOffset: 19,
    durationDays: 3,
    crewLeadKey: 'sam',
    address: { line1: '1427 S Clarkson Street', city: 'Denver', state: 'CO', zip: '80210' },
    contract_amount: 14900,
    estimated_revenue: 14900,
    estimated_cost: 10100,
    estimated_labor_hours: 72,
    air_monitoring_required: true,
    clearance_testing_required: true,
    inspection_required: true,
    special_instructions:
      'Sale closes 9/12 — clearance letter must be issued no later than 9/05. Homeowner works from home; confirm the morning of.',
  },
]

// One invoice per job — `uniq_invoices_job_id` enforces it at the database.
// Statuses are chosen to give the dashboard a real AR story: collected,
// outstanding, overdue (including a disputed partial payment), and a draft.
export const INVOICES = [
  {
    key: 'inv-frsd',
    jobKey: 'job-frsd',
    contactKey: 'yvonne',
    status: 'paid',
    issuedOffset: -30,
    dueDays: 45,
    subtotal: 126850,
    amount_paid: 126850,
    payment_terms: 'net_45',
    notes:
      'Final billing including the approved change order for the room 112 casework. Paid in full 18 days early.',
  },
  {
    key: 'inv-alpine',
    jobKey: 'job-alpine',
    contactKey: 'ray',
    status: 'sent',
    issuedOffset: -14,
    dueDays: 30,
    subtotal: 48500,
    amount_paid: 14550,
    payment_terms: 'net_30',
    notes: 'Deposit received on mobilisation; balance due on completion and clearance.',
  },
  {
    key: 'inv-cherry-p1',
    jobKey: 'job-cherry-phase1',
    contactKey: 'karen',
    status: 'overdue',
    issuedOffset: -68,
    dueDays: 30,
    subtotal: 27300,
    amount_paid: 19110,
    payment_terms: 'net_30',
    notes:
      'Partial payment received. Balance disputed pending the siding bid — Karen asked to roll it into the phase 2 contract.',
  },
  {
    key: 'inv-kessler',
    jobKey: 'job-kessler-active',
    contactKey: 'bill',
    status: 'overdue',
    issuedOffset: -52,
    dueDays: 30,
    subtotal: 5580,
    amount_paid: 0,
    payment_terms: 'net_30',
    notes: 'Mobilisation deposit. Second reminder sent — AP contact on leave until the 4th.',
  },
  {
    key: 'inv-alpine-p2',
    jobKey: 'job-alpine-phase2',
    contactKey: 'ray',
    status: 'draft',
    issuedOffset: 0,
    dueDays: 30,
    subtotal: 9400,
    amount_paid: 0,
    payment_terms: 'net_30',
    notes: 'Draft — hold until clearance passes.',
  },
]

// Properties are the physical locations. Jobs, surveys and opportunities all
// hang off an address, and contacts/companies relate to it — so the same
// property accumulates history as work repeats and as it changes hands.
//
// `contacts` links people to the address with a role. `is_current: false`
// records someone who used to be connected (a prior owner), which is what
// makes the property, rather than the contact, the durable record.
export const PROPERTIES = [
  {
    key: 'prop-jasmine',
    address_line1: '1180 Jasmine Street',
    city: 'Denver',
    state: 'CO',
    zip: '80220',
    property_type: 'residential_multi_family',
    notes:
      '36-unit garden complex, 1979. Boiler room TSI abated July 2026; remaining duct insulation being handled unit by unit.',
    contacts: [{ contactKey: 'ray', role: 'owner' }],
  },
  {
    key: 'prop-steele',
    address_line1: '1455 Steele Street',
    city: 'Denver',
    state: 'CO',
    zip: '80206',
    property_type: 'residential_multi_family',
    notes:
      '4-plex, 1973. Common-area TSI removed May 2026. Transite siding scheduled — tenants remain in occupancy throughout.',
    contacts: [
      { contactKey: 'karen', role: 'billing_contact' },
      { contactKey: 'doug', role: 'site_contact' },
    ],
  },
  {
    key: 'prop-holly',
    address_line1: '6500 Holly Street',
    city: 'Commerce City',
    state: 'CO',
    zip: '80022',
    property_type: 'government',
    notes:
      'Adams Elementary, 1968. 9x9 VAT abated across 19 rooms during the summer 2026 shutdown. Clearance passed before staff return.',
    contacts: [{ contactKey: 'yvonne', role: 'site_contact' }],
  },
  {
    key: 'prop-curtis',
    address_line1: '2100 Curtis Street',
    city: 'Denver',
    state: 'CO',
    zip: '80205',
    property_type: 'commercial',
    notes: '1955 two-storey commercial. Lead paint stabilisation ahead of tenant fit-out.',
    contacts: [{ contactKey: 'bill', role: 'site_contact' }],
  },
  {
    key: 'prop-clarkson',
    address_line1: '1427 S Clarkson Street',
    city: 'Denver',
    state: 'CO',
    zip: '80210',
    property_type: 'residential_single_family',
    notes:
      'Bungalow, 1958. Zonolite attic insulation. Sale pending — clearance letter required before closing.',
    contacts: [
      { contactKey: 'gregory', role: 'owner' },
      // Sold in 2024. Keeping the prior owner on the property is the point
      // of the record: the next crew sees who to ask about work predating
      // the current owner.
      { contactKey: 'harold', role: 'previous_owner', is_current: false },
    ],
  },
  {
    key: 'prop-32nd',
    address_line1: '3390 W 32nd Avenue',
    city: 'Denver',
    state: 'CO',
    zip: '80211',
    property_type: 'residential_single_family',
    notes: '1987 two-storey. Basement mould following an April sewer backup. Travelers claim open.',
    contacts: [{ contactKey: 'marisol', role: 'owner' }],
  },
  {
    key: 'prop-arapahoe',
    address_line1: '3300 Arapahoe Avenue',
    city: 'Boulder',
    state: 'CO',
    zip: '80303',
    property_type: 'industrial',
    notes:
      '41,000 sq ft light industrial, 1963. Pre-demolition survey ahead of redevelopment — roofing, TSI, floor tile and transite partitions all suspect.',
    contacts: [{ contactKey: 'nina', role: 'site_contact' }],
  },
  {
    key: 'prop-eudora',
    address_line1: '2214 Eudora Street',
    city: 'Denver',
    state: 'CO',
    zip: '80207',
    property_type: 'residential_single_family',
    notes: '1982 ranch. Ceiling texture sampling requested ahead of a kitchen remodel.',
    contacts: [{ contactKey: 'angela', role: 'owner' }],
  },
  {
    key: 'prop-marion',
    address_line1: '860 Marion Street',
    city: 'Denver',
    state: 'CO',
    zip: '80218',
    property_type: 'residential_single_family',
    notes:
      'Duct insulation removal quoted June 2026, lost on price to Mile High Environmental. Worth a follow-up in Q4.',
    contacts: [{ contactKey: 'peter', role: 'owner' }],
  },
]

// Analytical labs the company sends samples to.
export const LABS = [
  {
    key: 'rma',
    name: 'Rocky Mountain Analytical',
    contact_name: 'Denise Fowler',
    contact_email: 'mark.hope+demo.rma@asymmetric.pro',
    contact_phone: '(303) 555-0410',
    address: '1290 W Bayaud Avenue, Denver, CO 80223',
    notes: 'NVLAP accredited. Same-day PCM on air clearances if delivered before 2pm.',
  },
  {
    key: 'frontrange',
    name: 'Front Range Testing',
    contact_name: 'Owen Brackett',
    contact_email: 'mark.hope+demo.frontrange@asymmetric.pro',
    contact_phone: '(720) 555-0420',
    address: '8801 E Hampden Avenue, Denver, CO 80231',
    notes: 'Used for lead wipes and mould. AIHA-LAP accredited.',
  },
]

// Lab reports: samples ordered against surveys and jobs. Mix of received
// (results back) and still-ordered so the list shows both states.
export const LAB_REPORTS = [
  {
    key: 'lab-alpine-clearance',
    labKey: 'rma',
    propertyKey: 'prop-jasmine',
    contactKey: 'ray',
    sample_type: 'asbestos_air',
    status: 'received',
    orderedOffset: -17,
    receivedOffset: -16,
    sample_description: '5 clearance air samples, boiler room and mechanical chase (PCM).',
    notes: 'All five below 0.01 f/cc. Cleared first attempt at 0.004 f/cc.',
  },
  {
    key: 'lab-alpine-bulk',
    labKey: 'rma',
    propertyKey: 'prop-jasmine',
    contactKey: 'ray',
    sample_type: 'asbestos_bulk',
    status: 'received',
    orderedOffset: -39,
    receivedOffset: -37,
    sample_description: '6 bulk samples — pipe lagging and mudded fittings (PLM).',
    notes: 'Chrysotile 15-20% in lagging, 8% in fitting mud. Confirms RACM.',
  },
  {
    key: 'lab-frsd-bulk',
    labKey: 'rma',
    propertyKey: 'prop-holly',
    contactKey: 'yvonne',
    sample_type: 'asbestos_bulk',
    status: 'received',
    orderedOffset: -62,
    receivedOffset: -59,
    sample_description: '9 bulk samples — 9x9 floor tile and black mastic, rooms 100-118.',
    notes: 'Tile 3% chrysotile, mastic 5%. Both regulated.',
  },
  {
    key: 'lab-frsd-clearance',
    labKey: 'rma',
    propertyKey: 'prop-holly',
    contactKey: 'yvonne',
    sample_type: 'asbestos_air',
    status: 'received',
    orderedOffset: -33,
    receivedOffset: -32,
    sample_description: '18 clearance air samples across 19 rooms and the main corridor.',
    notes: 'All below limit. District cleared for staff return.',
  },
  {
    key: 'lab-kessler-paint',
    labKey: 'frontrange',
    propertyKey: 'prop-curtis',
    contactKey: 'bill',
    sample_type: 'lead_paint',
    status: 'received',
    orderedOffset: -14,
    receivedOffset: -11,
    sample_description: '8 paint chip samples — window trim, door casings, plaster walls.',
    notes: 'Window trim 1.8 mg/cm2, casings 1.2. Above the 1.0 action level.',
  },
  {
    key: 'lab-kessler-wipe',
    labKey: 'frontrange',
    propertyKey: 'prop-curtis',
    contactKey: 'bill',
    sample_type: 'lead_dust',
    status: 'ordered',
    orderedOffset: -1,
    sample_description: '12 clearance wipe samples — floors, sills and troughs, second floor.',
    notes: 'Awaiting results before the space is released to the tenant.',
  },
  {
    key: 'lab-duarte-mold',
    labKey: 'frontrange',
    propertyKey: 'prop-32nd',
    contactKey: 'marisol',
    sample_type: 'mold_surface',
    status: 'received',
    orderedOffset: -5,
    receivedOffset: -3,
    sample_description: '4 tape lifts — basement framing and drywall, north wall.',
    notes: 'Stachybotrys and Aspergillus/Penicillium present. Supports the claim scope.',
  },
  {
    key: 'lab-hahn-bulk',
    labKey: 'rma',
    propertyKey: 'prop-clarkson',
    contactKey: 'gregory',
    sample_type: 'asbestos_bulk',
    status: 'received',
    orderedOffset: -10,
    receivedOffset: -8,
    sample_description: '3 bulk samples — loose-fill attic vermiculite.',
    notes: 'Tremolite detected, trace. Handle as ACM per state guidance.',
  },
  {
    key: 'lab-baseline-survey',
    labKey: 'rma',
    propertyKey: 'prop-arapahoe',
    contactKey: 'nina',
    sample_type: 'asbestos_bulk',
    status: 'ordered',
    orderedOffset: -2,
    sample_description: '24 bulk samples — roofing, TSI, floor tile and transite partitions.',
    notes: 'Pre-demolition survey. Results needed before the abatement scope can be priced.',
  },
]

// Photo captions per survey, cycled to fill the requested photo count.
export const PHOTO_PLAN = {
  'srv-alpine': [
    { category: 'hazard', location: 'Boiler room — north wall', caption: 'TSI on 4" horizontal run, visible damage at hanger' },
    { category: 'hazard', location: 'Boiler room — ceiling', caption: 'Mudded fittings, 14 total across the run' },
    { category: 'overview', location: 'Boiler room', caption: 'Room overview from the stair landing' },
    { category: 'access', location: 'Basement stair', caption: 'Sole access route — no exterior door' },
  ],
  'srv-frsd': [
    { category: 'hazard', location: 'Room 104', caption: '9x9 VAT over black mastic, typical condition' },
    { category: 'hazard', location: 'Main corridor', caption: 'Tile lifting at the corridor expansion joint' },
    { category: 'overview', location: 'Room 112', caption: 'Built-in casework — suspect tile beneath' },
    { category: 'overview', location: 'Main corridor', caption: 'Corridor looking east toward the gym' },
    { category: 'access', location: 'Service entrance', caption: 'Loading area staged for waste-out' },
  ],
  'srv-cherry': [
    { category: 'hazard', location: 'North elevation', caption: 'Impact damage to transite panels at grade' },
    { category: 'overview', location: 'East elevation', caption: 'Panels intact, typical of three elevations' },
    { category: 'overview', location: 'Property', caption: 'Building overview from Steele Street' },
  ],
  'srv-kessler': [
    { category: 'hazard', location: 'Second floor — window bay', caption: 'Deteriorated LBP on window trim, XRF positive' },
    { category: 'hazard', location: 'Second floor — corridor', caption: 'Door casing paint failure' },
    { category: 'overview', location: 'Second floor', caption: 'Open office area ahead of fit-out' },
  ],
  'srv-hahn': [
    { category: 'hazard', location: 'Attic — south bay', caption: 'Zonolite loose-fill between joists' },
    { category: 'hazard', location: 'Attic — centre', caption: 'Depth check, approx. 6 inches typical' },
    { category: 'access', location: 'Hallway hatch', caption: 'Only attic access — scuttle hatch, 22x30' },
    { category: 'overview', location: 'Attic', caption: 'Attic overview toward the ridge' },
  ],
  'srv-duarte': [
    { category: 'hazard', location: 'Basement — north wall', caption: 'Growth on drywall to 18" above slab' },
    { category: 'hazard', location: 'Basement — framing', caption: 'Affected bottom plate and studs' },
    { category: 'overview', location: 'Basement', caption: 'Finished basement overview' },
  ],
}
