'use client'

import { useState, useEffect, useMemo } from 'react'
import { useRouter } from 'next/navigation'
import { format } from 'date-fns'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Calendar } from '@/components/ui/calendar'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import { ArrowLeft, CalendarIcon, Loader2, Search, Building2 } from 'lucide-react'
import { cn } from '@/lib/utils'
import { useToast } from '@/components/ui/use-toast'
import Link from 'next/link'

interface Customer {
  id: string
  name: string
  company_name: string | null
  first_name: string | null
  last_name: string | null
  email: string | null
  address_line1: string | null
  city: string | null
  state: string | null
  zip: string | null
}

interface PipelineStage {
  id: string
  name: string
  color: string
  probability: number
  stage_type?: string
}

export default function NewOpportunityPage() {
  const router = useRouter()
  const { toast } = useToast()

  const [loading, setLoading] = useState(false)
  const [loadingData, setLoadingData] = useState(true)
  const [customers, setCustomers] = useState<Customer[]>([])
  const [stages, setStages] = useState<PipelineStage[]>([])
  const [contactSearch, setContactSearch] = useState('')

  const [formData, setFormData] = useState({
    customer_id: '',
    name: '',
    nameAutoGenerated: true, // flips to false once the user types a custom name
    description: '',
    stage_id: '',
    estimated_value: '',
    expected_close_date: undefined as Date | undefined,
    hazard_type: '' as '' | 'asbestos' | 'mold' | 'lead' | 'vermiculite' | 'other',
    service_address_line1: '',
    service_city: '',
    service_state: '',
    service_zip: '',
  })

  useEffect(() => {
    async function fetchData() {
      try {
        const [customersRes, stagesRes] = await Promise.all([
          fetch('/api/customers?limit=500'),
          fetch('/api/pipeline/stages'),
        ])

        const customersData = await customersRes.json()
        const stagesData = await stagesRes.json()

        if (customersData.customers) {
          setCustomers(customersData.customers)
        } else if (Array.isArray(customersData)) {
          setCustomers(customersData)
        }
        if (Array.isArray(stagesData)) {
          setStages(stagesData)
          const defaultStage = stagesData.find(
            (s: PipelineStage) => !['won', 'lost'].includes(s.name.toLowerCase())
          )
          if (defaultStage) {
            setFormData(prev => ({ ...prev, stage_id: defaultStage.id }))
          }
        }
      } catch {
        toast({
          title: 'Error',
          description: 'Failed to load form data',
          variant: 'destructive',
        })
      } finally {
        setLoadingData(false)
      }
    }
    fetchData()
  }, [toast])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!formData.customer_id) {
      toast({ title: 'Error', description: 'Please select a customer', variant: 'destructive' })
      return
    }
    if (!formData.name) {
      toast({ title: 'Error', description: 'Please enter an opportunity name', variant: 'destructive' })
      return
    }
    if (!formData.stage_id) {
      toast({ title: 'Error', description: 'Please select a pipeline stage', variant: 'destructive' })
      return
    }

    setLoading(true)

    try {
      const response = await fetch('/api/pipeline', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          customer_id: formData.customer_id,
          name: formData.name,
          description: formData.description || undefined,
          stage_id: formData.stage_id,
          estimated_value: formData.estimated_value
            ? parseFloat(formData.estimated_value)
            : undefined,
          expected_close_date: formData.expected_close_date
            ? format(formData.expected_close_date, 'yyyy-MM-dd')
            : undefined,
          hazard_types: formData.hazard_type ? [formData.hazard_type] : undefined,
          service_address_line1: formData.service_address_line1 || undefined,
          service_city: formData.service_city || undefined,
          service_state: formData.service_state || undefined,
          service_zip: formData.service_zip || undefined,
        }),
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || 'Failed to create opportunity')
      }

      const opportunity = await response.json()
      toast({
        title: 'Opportunity created',
        description: `${opportunity.name} has been added to your pipeline`,
      })
      router.push('/crm/opportunities')
    } catch (error) {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to create opportunity',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }

  const selectedCustomer = customers.find(c => c.id === formData.customer_id)

  const filteredCustomers = useMemo(() => {
    if (!contactSearch) return customers
    const q = contactSearch.toLowerCase()
    return customers.filter(c =>
      (c.name || '').toLowerCase().includes(q) ||
      (c.first_name || '').toLowerCase().includes(q) ||
      (c.last_name || '').toLowerCase().includes(q) ||
      (c.company_name || '').toLowerCase().includes(q) ||
      (c.email || '').toLowerCase().includes(q)
    )
  }, [customers, contactSearch])

  const handleSelectCustomer = (customerId: string) => {
    const customer = customers.find(c => c.id === customerId)
    setFormData(prev => ({
      ...prev,
      customer_id: customerId,
      // Auto-fill address from customer if empty
      service_address_line1: prev.service_address_line1 || customer?.address_line1 || '',
      service_city: prev.service_city || customer?.city || '',
      service_state: prev.service_state || customer?.state || '',
      service_zip: prev.service_zip || customer?.zip || '',
    }))
  }

  // Generate a name from Contact/Company + Hazard + Date when the
  // user hasn't typed their own. Matches the CompanyName_Hazard_MM/DD/YY
  // convention we've been using informally (e.g. WillowMeadow_Mold_4/22/26).
  function buildAutoName(
    customer: Customer | undefined,
    hazard: string,
    stage: PipelineStage | undefined,
  ): string {
    if (!customer) return ''
    const cleanCompany = (customer.company_name || '').replace(/[^a-zA-Z0-9]/g, '')
    const cleanPerson = [customer.first_name, customer.last_name]
      .filter(Boolean)
      .join('')
      .replace(/[^a-zA-Z0-9]/g, '')
    const who = cleanCompany || cleanPerson || customer.name.replace(/[^a-zA-Z0-9]/g, '')
    const hazardPart = hazard
      ? hazard.charAt(0).toUpperCase() + hazard.slice(1)
      : 'Opportunity'
    const now = new Date()
    const datePart = `${now.getMonth() + 1}/${now.getDate()}/${String(now.getFullYear()).slice(-2)}`
    const parts = [who, hazardPart, datePart].filter(Boolean)
    const stageSuffix = stage && ['won', 'lost'].includes(stage.stage_type ?? stage.name.toLowerCase())
      ? `_${stage.name}`
      : ''
    return parts.join('_') + stageSuffix
  }

  const autoName = useMemo(
    () =>
      buildAutoName(
        customers.find(c => c.id === formData.customer_id),
        formData.hazard_type,
        stages.find(s => s.id === formData.stage_id),
      ),
    [customers, formData.customer_id, formData.hazard_type, formData.stage_id, stages],
  )

  // Keep the name field synced with the auto-generated value unless the
  // user has taken over by typing something custom.
  useEffect(() => {
    if (formData.nameAutoGenerated && autoName && formData.name !== autoName) {
      setFormData(prev => ({ ...prev, name: autoName }))
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoName, formData.nameAutoGenerated])

  const selectedStage = stages.find(s => s.id === formData.stage_id)
  const weightedValue = formData.estimated_value && selectedStage
    ? parseFloat(formData.estimated_value) * (selectedStage.probability / 100)
    : 0

  return (
    <div className="max-w-2xl mx-auto">
      <div className="flex items-center gap-2 mb-6">
        <Button variant="ghost" size="icon" asChild aria-label="Back to opportunities">
          <Link href="/crm/opportunities">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <h1 className="text-2xl font-bold">New Opportunity</h1>
          <p className="text-muted-foreground">Add a new opportunity to your sales pipeline</p>
        </div>
      </div>

      <form onSubmit={handleSubmit}>
        <div className="space-y-6">
          <Card>
            <CardHeader><CardTitle>Contact & Location</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label>Select Contact *</Label>
                {selectedCustomer ? (
                  // Chosen contact collapses to a card with a Change link;
                  // the long search list only reopens if the user clicks Change.
                  <div className="rounded-lg border bg-muted/30 p-3 flex items-start justify-between gap-3">
                    <div className="min-w-0 flex-1 text-sm space-y-1">
                      <div className="font-medium truncate">
                        {[selectedCustomer.first_name, selectedCustomer.last_name].filter(Boolean).join(' ') || selectedCustomer.name}
                      </div>
                      {selectedCustomer.company_name && (
                        <div className="flex items-center gap-1 text-muted-foreground text-xs">
                          <Building2 className="h-3 w-3" />
                          <span className="truncate">{selectedCustomer.company_name}</span>
                        </div>
                      )}
                      {selectedCustomer.email && (
                        <div className="text-muted-foreground text-xs truncate">{selectedCustomer.email}</div>
                      )}
                    </div>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={() => {
                        setFormData(prev => ({ ...prev, customer_id: '' }))
                        setContactSearch('')
                      }}
                    >
                      Change
                    </Button>
                  </div>
                ) : (
                  <>
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        value={contactSearch}
                        onChange={(e) => setContactSearch(e.target.value)}
                        placeholder={loadingData ? 'Loading contacts...' : 'Start typing a name, company, or email…'}
                        className="pl-9"
                        disabled={loadingData}
                        autoFocus
                      />
                    </div>
                    {/* Results only appear once the user starts typing, so
                        the form doesn't open with a wall of 50 contacts. */}
                    {contactSearch.trim().length > 0 && (
                      <div className="max-h-64 overflow-y-auto rounded-md border">
                        {loadingData ? (
                          <div className="px-3 py-4 text-sm text-muted-foreground text-center">Loading contacts…</div>
                        ) : filteredCustomers.length === 0 ? (
                          <div className="px-3 py-4 text-sm text-muted-foreground text-center">
                            No contacts match your search.
                          </div>
                        ) : (
                          <ul className="divide-y">
                            {filteredCustomers.slice(0, 15).map((customer) => {
                              const displayName = [customer.first_name, customer.last_name].filter(Boolean).join(' ') || customer.name
                              return (
                                <li key={customer.id}>
                                  <button
                                    type="button"
                                    onClick={() => handleSelectCustomer(customer.id)}
                                    className={cn(
                                      'w-full text-left px-3 py-2 hover:bg-accent flex items-center justify-between gap-2',
                                    )}
                                  >
                                    <div className="min-w-0 flex-1">
                                      <div className="text-sm font-medium truncate">{displayName || 'Unnamed'}</div>
                                      <div className="text-xs text-muted-foreground truncate flex items-center gap-2">
                                        {customer.company_name && (
                                          <span className="inline-flex items-center gap-1">
                                            <Building2 className="h-3 w-3" />
                                            {customer.company_name}
                                          </span>
                                        )}
                                        {customer.email && <span>{customer.email}</span>}
                                      </div>
                                    </div>
                                  </button>
                                </li>
                              )
                            })}
                          </ul>
                        )}
                      </div>
                    )}
                    {contactSearch.trim().length > 0 && filteredCustomers.length > 15 && (
                      <p className="text-xs text-muted-foreground">
                        Showing first 15 of {filteredCustomers.length} — keep typing to narrow down.
                      </p>
                    )}
                  </>
                )}
              </div>

              {/* Site Address */}
              <div className="space-y-2 pt-2">
                <Label>Site / Property Address</Label>
                <Input
                  value={formData.service_address_line1}
                  onChange={(e) => setFormData(prev => ({ ...prev, service_address_line1: e.target.value }))}
                  placeholder="Street address"
                />
                <div className="grid grid-cols-3 gap-2">
                  <Input
                    value={formData.service_city}
                    onChange={(e) => setFormData(prev => ({ ...prev, service_city: e.target.value }))}
                    placeholder="City"
                  />
                  <Input
                    value={formData.service_state}
                    onChange={(e) => setFormData(prev => ({ ...prev, service_state: e.target.value }))}
                    placeholder="State"
                    maxLength={2}
                  />
                  <Input
                    value={formData.service_zip}
                    onChange={(e) => setFormData(prev => ({ ...prev, service_zip: e.target.value }))}
                    placeholder="ZIP"
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle>Opportunity Details</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label>Hazard Type</Label>
                <Select
                  value={formData.hazard_type}
                  onValueChange={(value) =>
                    setFormData(prev => ({
                      ...prev,
                      hazard_type: value as typeof prev.hazard_type,
                    }))
                  }
                >
                  <SelectTrigger><SelectValue placeholder="Select hazard" /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="asbestos">Asbestos</SelectItem>
                    <SelectItem value="mold">Mold</SelectItem>
                    <SelectItem value="lead">Lead</SelectItem>
                    <SelectItem value="vermiculite">Vermiculite</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label>Opportunity Name *</Label>
                  {!formData.nameAutoGenerated && autoName && (
                    <button
                      type="button"
                      onClick={() =>
                        setFormData(prev => ({ ...prev, nameAutoGenerated: true, name: autoName }))
                      }
                      className="text-xs text-primary hover:underline"
                    >
                      Reset to auto
                    </button>
                  )}
                </div>
                <Input
                  value={formData.name}
                  onChange={(e) =>
                    setFormData(prev => ({
                      ...prev,
                      name: e.target.value,
                      nameAutoGenerated: false,
                    }))
                  }
                  placeholder="Pick a contact + hazard to auto-generate…"
                />
                <p className="text-xs text-muted-foreground">
                  {formData.nameAutoGenerated
                    ? 'Auto-generated from contact + hazard + today. Type to override.'
                    : 'Custom name (auto-generation is off)'}
                </p>
              </div>
              <div className="space-y-2">
                <Label>Description</Label>
                <Textarea
                  value={formData.description}
                  onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                  placeholder="Brief description of the opportunity"
                  rows={3}
                />
              </div>
              <div className="space-y-2">
                <Label>Pipeline Stage *</Label>
                <Select
                  value={formData.stage_id}
                  onValueChange={(value) => setFormData(prev => ({ ...prev, stage_id: value }))}
                  disabled={loadingData}
                >
                  <SelectTrigger><SelectValue placeholder="Select a stage" /></SelectTrigger>
                  <SelectContent>
                    {stages.map(stage => (
                      <SelectItem key={stage.id} value={stage.id}>
                        <div className="flex items-center gap-2">
                          <div className="w-3 h-3 rounded-full" style={{ backgroundColor: stage.color }} />
                          {stage.name} ({stage.probability}%)
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle>Value & Timeline</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Estimated Value ($)</Label>
                  <Input
                    type="number" min="0" step="100"
                    value={formData.estimated_value}
                    onChange={(e) => setFormData(prev => ({ ...prev, estimated_value: e.target.value }))}
                    placeholder="e.g., 50000"
                  />
                </div>
                <div className="space-y-2">
                  <Label>Weighted Value</Label>
                  <Input
                    value={weightedValue.toLocaleString('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0 })}
                    disabled className="bg-muted"
                  />
                  {selectedStage && (
                    <p className="text-xs text-muted-foreground">Based on {selectedStage.probability}% probability</p>
                  )}
                </div>
              </div>
              <div className="space-y-2">
                <Label>Expected Close Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      type="button"
                      variant="outline"
                      className={cn('w-full justify-start text-left font-normal', !formData.expected_close_date && 'text-muted-foreground')}
                    >
                      <CalendarIcon className="mr-2 h-4 w-4" />
                      {formData.expected_close_date ? format(formData.expected_close_date, 'PPP') : 'Pick a date'}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0">
                    <Calendar
                      mode="single"
                      selected={formData.expected_close_date}
                      onSelect={(date) => setFormData(prev => ({ ...prev, expected_close_date: date }))}
                      initialFocus
                    />
                  </PopoverContent>
                </Popover>
              </div>
            </CardContent>
          </Card>

          <div className="flex gap-4">
            <Button type="button" variant="outline" asChild className="flex-1">
              <Link href="/crm/opportunities">Cancel</Link>
            </Button>
            <Button type="submit" disabled={loading} className="flex-1">
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              {loading ? 'Creating...' : 'Create Opportunity'}
            </Button>
          </div>
        </div>
      </form>
    </div>
  )
}
